flowchart TD
        A(["Start"])
        B{{"s=0; num1=0; num2=0;"}}
        C[/"Input num1, num2"/]
        D[s=num1+num2]
        E[/"Output s"/]
        F(["End"])
    
    %% Edge connections between nodes
        A --> B
        B --> C
        C --> D
        D --> E
        E --> F